In [1]:
import numpy as np

In [2]:
from numpy.lib.stride_tricks import as_strided

In [3]:
A = np.array([[20.0,200,-5,23],[-13,134,119,100],[120,32,49,25],[-120,12,9,23]])

In [28]:
# https://stackoverflow.com/a/74939121/11296354
def maxpool2d_numpy(X,kd1,kd2,s1,s2):
    d1,d2=X.shape
    out_d1=(d1-kd1)//s1+1
    out_d2=(d2-kd2)//s2+1
    return np.max(as_strided(X,shape=(out_d1,out_d2,kd1,kd2),strides=tuple(i*X.itemsize for i in (s1*d1,s2,d2,1))),axis=(2,3))

In [29]:
maxpool2d_numpy(A,2,2,2,2)

array([[200., 119.],
       [120.,  49.]])

In [31]:
# https://stackoverflow.com/a/42463491/11296354
from skimage.measure import block_reduce

In [6]:
block_reduce(A,(2,2),np.max)

array([[200., 119.],
       [120.,  49.]])

In [7]:
import apple

In [8]:
maxpool2d=apple.jit("([(⋉)/* _1e100 (x::M float)] ⨳ {2∘2,2∘2})")

In [9]:
maxpool2d(A)

array([[200., 119.],
       [120.,  49.]])