In [1]:
import numpy as np

In [2]:
bs=np.random.rand(1024,1024)

In [3]:
%timeit bs@bs

8.41 ms ± 109 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
import apple

In [5]:
mul=apple.jit("[(x::M ₁₀₂₄,₁₀₂₄ float)%.(y::M ₁₀₂₄,₁₀₂₄ float)]")

In [6]:
mulT=apple.jit("[(x::M ₁₀₂₄,₁₀₂₄ float)%.|:(y::M ₁₀₂₄,₁₀₂₄ float)]")

In [7]:
mul(bs,bs)

array([[257.26030546, 249.83078482, 255.56100649, ..., 246.20256677,
        263.22037797, 262.79265545],
       [267.39701946, 264.21177235, 254.85459247, ..., 260.87955432,
        276.2058817 , 268.21432766],
       [247.16382253, 239.33191272, 249.11109189, ..., 244.54275481,
        258.7221744 , 252.77044845],
       ...,
       [254.18600757, 245.17448741, 252.89448722, ..., 242.36546951,
        256.29964452, 256.25213555],
       [257.01744791, 250.38894776, 249.9760852 , ..., 249.30948827,
        261.03219482, 253.30003335],
       [262.03360847, 250.83101784, 258.11109115, ..., 257.25670231,
        270.2317883 , 262.76957259]])

In [8]:
bs@bs

array([[257.26030546, 249.83078482, 255.56100649, ..., 246.20256677,
        263.22037797, 262.79265545],
       [267.39701946, 264.21177235, 254.85459247, ..., 260.87955432,
        276.2058817 , 268.21432766],
       [247.16382253, 239.33191272, 249.11109189, ..., 244.54275481,
        258.7221744 , 252.77044845],
       ...,
       [254.18600757, 245.17448741, 252.89448722, ..., 242.36546951,
        256.29964452, 256.25213555],
       [257.01744791, 250.38894776, 249.9760852 , ..., 249.30948827,
        261.03219482, 253.30003335],
       [262.03360847, 250.83101784, 258.11109115, ..., 257.25670231,
        270.2317883 , 262.76957259]])

In [9]:
bs@bs.T

array([[337.13046517, 264.669609  , 249.1652165 , ..., 250.76271047,
        247.70597997, 258.41232767],
       [264.669609  , 352.07906144, 256.59274281, ..., 261.06662929,
        265.64051281, 271.91539599],
       [249.1652165 , 256.59274281, 321.6757977 , ..., 244.49526199,
        244.56799361, 253.58892779],
       ...,
       [250.76271047, 261.06662929, 244.49526199, ..., 328.3687971 ,
        245.83031186, 251.79725135],
       [247.70597997, 265.64051281, 244.56799361, ..., 245.83031186,
        337.23628049, 256.80905423],
       [258.41232767, 271.91539599, 253.58892779, ..., 251.79725135,
        256.80905423, 354.17532093]])

In [10]:
mulT(bs,bs)

array([[337.13046517, 264.669609  , 249.1652165 , ..., 250.76271047,
        247.70597997, 258.41232767],
       [264.669609  , 352.07906144, 256.59274281, ..., 261.06662929,
        265.64051281, 271.91539599],
       [249.1652165 , 256.59274281, 321.6757977 , ..., 244.49526199,
        244.56799361, 253.58892779],
       ...,
       [250.76271047, 261.06662929, 244.49526199, ..., 328.3687971 ,
        245.83031186, 251.79725135],
       [247.70597997, 265.64051281, 244.56799361, ..., 245.83031186,
        337.23628049, 256.80905423],
       [258.41232767, 271.91539599, 253.58892779, ..., 251.79725135,
        256.80905423, 354.17532093]])

In [11]:
%timeit mul(bs,bs)

252 ms ± 3.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
%timeit mulT(bs,bs)

322 ms ± 4.69 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
%timeit bs@bs.T

8.56 ms ± 99.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
