In [1]:
import numpy as np

In [2]:
bs=np.random.rand(1024,1024)

In [3]:
%timeit bs@bs

8.33 ms ± 272 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
import apple

In [5]:
mul=apple.jit("[(x::M ₁₀₂₄,₁₀₂₄ float)%.(y::M ₁₀₂₄,₁₀₂₄ float)]")

In [6]:
mulT=apple.jit("[(x::M ₁₀₂₄,₁₀₂₄ float)%.|:(y::M ₁₀₂₄,₁₀₂₄ float)]")

In [7]:
mul(bs,bs)

array([[252.26820045, 255.60129043, 258.00776936, ..., 250.60742662,
        257.71309095, 253.09927798],
       [250.23574432, 255.49080087, 260.87013084, ..., 251.16904578,
        263.09863404, 258.26231113],
       [253.76240442, 249.85262399, 250.15462469, ..., 248.4012046 ,
        260.95583889, 251.55704508],
       ...,
       [253.48143879, 257.96624582, 264.39715517, ..., 262.04599744,
        261.58959491, 264.01988062],
       [255.04591598, 256.59343761, 261.38318428, ..., 254.51382203,
        269.30672524, 260.65687114],
       [264.91036855, 257.1797689 , 270.06335585, ..., 259.17753583,
        267.31236189, 264.19735528]])

In [8]:
bs@bs

array([[252.26820045, 255.60129043, 258.00776936, ..., 250.60742662,
        257.71309095, 253.09927798],
       [250.23574432, 255.49080087, 260.87013084, ..., 251.16904578,
        263.09863404, 258.26231113],
       [253.76240442, 249.85262399, 250.15462469, ..., 248.4012046 ,
        260.95583889, 251.55704508],
       ...,
       [253.48143879, 257.96624582, 264.39715517, ..., 262.04599744,
        261.58959491, 264.01988062],
       [255.04591598, 256.59343761, 261.38318428, ..., 254.51382203,
        269.30672524, 260.65687114],
       [264.91036855, 257.1797689 , 270.06335585, ..., 259.17753583,
        267.31236189, 264.19735528]])

In [9]:
bs@bs.T

array([[342.82368465, 250.45846093, 254.04530759, ..., 259.44023679,
        257.07829204, 260.18498253],
       [250.45846093, 334.87064545, 253.20983946, ..., 257.50941673,
        260.52209098, 261.38537765],
       [254.04530759, 253.20983946, 337.35414138, ..., 257.48709845,
        257.89255997, 258.16025463],
       ...,
       [259.44023679, 257.50941673, 257.48709845, ..., 351.06753364,
        266.59457169, 266.86833622],
       [257.07829204, 260.52209098, 257.89255997, ..., 266.59457169,
        348.92959703, 266.12742877],
       [260.18498253, 261.38537765, 258.16025463, ..., 266.86833622,
        266.12742877, 352.61554708]])

In [10]:
mulT(bs,bs)

array([[342.82368465, 250.45846093, 254.04530759, ..., 259.44023679,
        257.07829204, 260.18498253],
       [250.45846093, 334.87064545, 253.20983946, ..., 257.50941673,
        260.52209098, 261.38537765],
       [254.04530759, 253.20983946, 337.35414138, ..., 257.48709845,
        257.89255997, 258.16025463],
       ...,
       [259.44023679, 257.50941673, 257.48709845, ..., 351.06753364,
        266.59457169, 266.86833622],
       [257.07829204, 260.52209098, 257.89255997, ..., 266.59457169,
        348.92959703, 266.12742877],
       [260.18498253, 261.38537765, 258.16025463, ..., 266.86833622,
        266.12742877, 352.61554708]])

In [11]:
%timeit mul(bs,bs)

168 ms ± 1.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%timeit mulT(bs,bs)

152 ms ± 467 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit bs@bs.T

8.9 ms ± 125 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
